### ISSUE TITLE
nse install instructions

### ISSUE THREAD

**Issue by r00t-3xp10it** [OCSAF/freevulnsearch#2]
in Installation:

    In KALI LINUX™ for example: /usr/share/nmap/scripts/

you have forgot to update nse database

      sudo nmap --script-updatedb

The above command it will update nse database with the recent script,
just like in metasploit we update msfdb database with reload_all command ..

**Comment by OCSAF** [comment]
Thanks for your feedback. You're right, the updatedb command should be executed for the correct assignment. I did some tests with the categories (safe, vuln), e.g. nmap -sV --script safe <IP>. 
The script should be run separately with -sV if possible for high stability with the API and not integrated into a category. I will continue testing and add this note in the next release.

**Comment by r00t-3xp10it** [comment]
Exelent ..because i normally call vuln categorie in my scans ..

**Comment by OCSAF** [comment]
I have removed the category assignment to safe and vuln in the script and made an adjustment of the README.md with explanations. Thanks for the inputs.
